### ISSUE TITLE
ZigBeeDevice getEnergy doesn't exist

### ISSUE THREAD

**Issue by lucasvdh** [athombv/node-homey-meshdriver#146]
In my case this happens for the Ikea SignalRepeater device.

```
2019-09-11 17:55:10 [log] [IkeaTradfriApp] init
/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:90
                let energy = this.getEnergy();
                                  ^

TypeError: this.getEnergy is not a function
    at SignalRepeater._setEnergyObjectByProductId (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:90:21)
    at SignalRepeater.onInit (/node_modules/homey-meshdriver/lib/zigbee/ZigBeeDevice.js:60:8)
    at SignalRepeater.__onInit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1603)
    at emitNone (events.js:106:13)
    at SignalRepeater.emit (events.js:208:7)

```

**Comment by lucasvdh** [comment]
Found out that this has been added in Homey v3, should the meshdriver already depend on this though? Break a few of my devices.

**Comment by RobinBol** [comment]
You are completely right, should be fixed, new deployment is building.
