### ISSUE TITLE
printNode fails on devices without battery

### ISSUE THREAD

**Issue by OliverIckler** [athombv/node-homey-meshdriver#91]
Wenn calling printNode on a device that does not support battery (like my devolo plug) the app crashes with the following error: 
/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:910
                this.log('- Battery:', this.node.battery);
                                                 ^

TypeError: Cannot read property 'battery' of undefined
    at MyDevice.printNode (/node_modules/homey-meshdriver/lib/zwave/ZwaveDevice.js:910:36)
    at MyDevice.onInit (/lib/devolodevice.js:13:14)
    at MyDevice.onInit (/drivers/mt2646/device.js:11:15)
    at MyDevice.__onInit (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Device.js:1:1605)
    at emitNone (events.js:106:13)
    at MyDevice.emit (events.js:208:7)
    at ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2272)
    at MyDriver.ready (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:3378)
    at MyDevice.r.on.on.on.once.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js:1:2259)
    at Object.onceWrapper (events.js:315:30)

**Comment by RobinBol** [comment]
This should not happen, the `node` property should always be available. Can you reproduce this consistently?

**Comment by RobinBol** [comment]
@OliverIckler Please let us know if this is still an issue for you and check my previous comment.

**Comment by RobinBol** [comment]
Closing due to inactivity.

**Comment by caseda** [comment]
For future reference:

`onInit()` is used here instead of the `onMeshInit()`
